"""empty message

Revision ID: 340a38d34179
Revises: b920875f7582
Create Date: 2025-08-04 17:50:00.950023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340a38d34179'
down_revision: Union[str, Sequence[str], None] = 'b920875f7582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cars_customer_id_fkey'), 'cars', type_='foreignkey')
    op.alter_column('servicelogs', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('servicelogs', 'mileage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('servicetasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workshops', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workshops', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workshops', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workshops', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workshops', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('servicetasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('servicelogs', 'mileage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servicelogs', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(op.f('cars_customer_id_fkey'), 'cars', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
