"""Add extended fields to workshop

Revision ID: 3ebc277bf994
Revises: 36942efdcef7
Create Date: 2025-07-31 16:25:57.913721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ebc277bf994'
down_revision: Union[str, Sequence[str], None] = '36942efdcef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshops', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('workshops', sa.Column('website', sa.String(), nullable=True))
    op.add_column('workshops', sa.Column('street_address', sa.String(), nullable=True))
    op.add_column('workshops', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('workshops', sa.Column('country', sa.String(), nullable=True))
    op.add_column('workshops', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('workshops', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('workshops', sa.Column('org_number', sa.String(), nullable=True))
    op.add_column('workshops', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('workshops', sa.Column('opening_hours', sa.String(), nullable=True))
    op.add_column('workshops', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('workshops', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workshops', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workshops', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('workshops', 'notes')
    op.drop_column('workshops', 'opening_hours')
    op.drop_column('workshops', 'active')
    op.drop_column('workshops', 'org_number')
    op.drop_column('workshops', 'longitude')
    op.drop_column('workshops', 'latitude')
    op.drop_column('workshops', 'country')
    op.drop_column('workshops', 'postal_code')
    op.drop_column('workshops', 'street_address')
    op.drop_column('workshops', 'website')
    op.drop_column('workshops', 'phone')
    # ### end Alembic commands ###
