"""servicelogs change

Revision ID: 4a93b80179f9
Revises: 3ebc277bf994
Create Date: 2025-08-02 13:33:42.371562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a93b80179f9'
down_revision: Union[str, Sequence[str], None] = '3ebc277bf994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicelogs',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('work_performed', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicelogs_id'), 'servicelogs', ['id'], unique=True)
    op.create_table('servicetasks',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('service_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_log_id'], ['servicelogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicetasks_id'), 'servicetasks', ['id'], unique=True)
    op.drop_index(op.f('ix_service_logs_id'), table_name='service_logs')
    op.drop_table('service_logs')
    op.alter_column('workshops', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workshops', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('service_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=True),
    sa.Column('work_performed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('mileage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name=op.f('service_logs_car_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('service_logs_pkey'))
    )
    op.create_index(op.f('ix_service_logs_id'), 'service_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_servicetasks_id'), table_name='servicetasks')
    op.drop_table('servicetasks')
    op.drop_index(op.f('ix_servicelogs_id'), table_name='servicelogs')
    op.drop_table('servicelogs')
    # ### end Alembic commands ###
