"""Lade till autonexo

Revision ID: 7c24d7d6950f
Revises: 340a38d34179
Create Date: 2025-08-10 20:18:45.174276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c24d7d6950f'
down_revision: Union[str, Sequence[str], None] = '340a38d34179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshops', sa.Column('autonexo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshops', 'autonexo')
    # ### end Alembic commands ###
