"""tog bort workshop

Revision ID: b920875f7582
Revises: e7e372daa95a
Create Date: 2025-08-02 17:27:35.267089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b920875f7582'
down_revision: Union[str, Sequence[str], None] = 'e7e372daa95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servicelogs', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('servicelogs', 'mileage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servicetasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workshops', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('servicetasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('servicelogs', 'mileage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servicelogs', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
