"""Add workshop_id to service_logs

Revision ID: cfe47b280a29
Revises: 4a93b80179f9
Create Date: 2025-08-02 17:17:01.376388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe47b280a29'
down_revision: Union[str, Sequence[str], None] = '4a93b80179f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicelogs', sa.Column('workshop_id', sa.Integer(), nullable=True))
    op.alter_column('servicelogs', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('servicelogs', 'mileage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_servicelogs_id'), table_name='servicelogs')
    op.create_index(op.f('ix_servicelogs_id'), 'servicelogs', ['id'], unique=False)
    op.create_foreign_key(None, 'servicelogs', 'workshops', ['workshop_id'], ['id'], ondelete='SET NULL')
    op.alter_column('servicetasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_servicetasks_id'), table_name='servicetasks')
    op.create_index(op.f('ix_servicetasks_id'), 'servicetasks', ['id'], unique=False)
    op.alter_column('workshops', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workshops', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workshops', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_servicetasks_id'), table_name='servicetasks')
    op.create_index(op.f('ix_servicetasks_id'), 'servicetasks', ['id'], unique=True)
    op.alter_column('servicetasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'servicelogs', type_='foreignkey')
    op.drop_index(op.f('ix_servicelogs_id'), table_name='servicelogs')
    op.create_index(op.f('ix_servicelogs_id'), 'servicelogs', ['id'], unique=True)
    op.alter_column('servicelogs', 'mileage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('servicelogs', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('servicelogs', 'workshop_id')
    # ### end Alembic commands ###
