"""fixade pris på upsell så de adderades till totalsum

Revision ID: 063b9c4cb7c5
Revises: 03a7905b1b77
Create Date: 2025-09-07 17:35:09.014966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '063b9c4cb7c5'
down_revision: Union[str, Sequence[str], None] = '03a7905b1b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
