"""commit

Revision ID: 18904299e008
Revises: f8cf0e7f1ecc
Create Date: 2025-08-18 16:18:33.627218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18904299e008'
down_revision: Union[str, Sequence[str], None] = 'f8cf0e7f1ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baybookings', sa.Column('chain_token', sa.String(), nullable=True))
    op.create_index('ix_baybooking_chain_token', 'baybookings', ['chain_token'], unique=False)
    op.create_index(op.f('ix_baybookings_chain_token'), 'baybookings', ['chain_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_baybookings_chain_token'), table_name='baybookings')
    op.drop_index('ix_baybooking_chain_token', table_name='baybookings')
    op.drop_column('baybookings', 'chain_token')
    # ### end Alembic commands ###
