"""lade till sista ändringarna för booking confirmation

Revision ID: 4ce9622e0983
Revises: bc094347e154
Create Date: 2025-08-18 11:04:54.159186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce9622e0983'
down_revision: Union[str, Sequence[str], None] = 'bc094347e154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baybookings', sa.Column('service_item_id', sa.Integer(), nullable=True))
    op.add_column('baybookings', sa.Column('actual_minutes_spent', sa.Integer(), nullable=True))
    op.add_column('baybookings', sa.Column('billed_from_time', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_baybookings_service_item_id'), 'baybookings', ['service_item_id'], unique=False)
    op.create_foreign_key(None, 'baybookings', 'workshop_service_items', ['service_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'baybookings', type_='foreignkey')
    op.drop_index(op.f('ix_baybookings_service_item_id'), table_name='baybookings')
    op.drop_column('baybookings', 'billed_from_time')
    op.drop_column('baybookings', 'actual_minutes_spent')
    op.drop_column('baybookings', 'service_item_id')
    # ### end Alembic commands ###
