"""lade till request_only på serviceitem

Revision ID: 743594884408
Revises: ce8690aa8867
Create Date: 2025-08-24 11:37:04.594744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743594884408'
down_revision: Union[str, Sequence[str], None] = 'ce8690aa8867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshop_service_items', sa.Column('request_only', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshop_service_items', 'request_only')
    # ### end Alembic commands ###
