"""fixade nullable på price_type

Revision ID: 8e1fcb9598a2
Revises: 743594884408
Create Date: 2025-08-24 12:46:22.815759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1fcb9598a2'
down_revision: Union[str, Sequence[str], None] = '743594884408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workshop_service_items', 'price_type',
               existing_type=sa.VARCHAR(length=6),
               nullable=True,
               existing_server_default=sa.text("'hourly'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workshop_service_items', 'price_type',
               existing_type=sa.VARCHAR(length=6),
               nullable=False,
               existing_server_default=sa.text("'hourly'::character varying"))
    # ### end Alembic commands ###
