"""lade till mer prisinfo kopplat till bokning

Revision ID: 9e16335c27f2
Revises: 4a8260223725
Create Date: 2025-08-16 15:45:21.313534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e16335c27f2'
down_revision: Union[str, Sequence[str], None] = '4a8260223725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baybookings', sa.Column('price_net_ore', sa.Integer(), nullable=True))
    op.add_column('baybookings', sa.Column('price_gross_ore', sa.Integer(), nullable=True))
    op.add_column('baybookings', sa.Column('vat_percent', sa.Integer(), nullable=True))
    op.add_column('baybookings', sa.Column('price_note', sa.String(), nullable=True))
    op.add_column('baybookings', sa.Column('price_is_custom', sa.Boolean(), nullable=True))
    op.add_column('baybookings', sa.Column('final_price_ore', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baybookings', 'final_price_ore')
    op.drop_column('baybookings', 'price_is_custom')
    op.drop_column('baybookings', 'price_note')
    op.drop_column('baybookings', 'vat_percent')
    op.drop_column('baybookings', 'price_gross_ore')
    op.drop_column('baybookings', 'price_net_ore')
    # ### end Alembic commands ###
