"""lade till customer klasser

Revision ID: a18e5aa273ca
Revises: 18904299e008
Create Date: 2025-08-19 16:20:51.454949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18e5aa273ca'
down_revision: Union[str, Sequence[str], None] = '18904299e008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_cars',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('is_primary_owner', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name='ck_cc_valid_range'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'car_id')
    )
    op.create_index('ix_cc_car', 'customer_cars', ['car_id'], unique=False)
    op.create_index('ix_cc_customer', 'customer_cars', ['customer_id'], unique=False)
    op.create_index('ix_car_regnr', 'cars', ['registration_number'], unique=False)
    op.drop_constraint(op.f('cars_customer_id_fkey'), 'cars', type_='foreignkey')
    op.drop_column('cars', 'customer_id')
    op.add_column('customers', sa.Column('workshop_id', sa.Integer(), nullable=False))
    op.alter_column('customers', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customers', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('customers_email_key'), 'customers', type_='unique')
    op.create_index('ix_customer_workshop', 'customers', ['workshop_id'], unique=False)
    op.create_index(op.f('ix_customers_workshop_id'), 'customers', ['workshop_id'], unique=False)
    op.create_unique_constraint('uq_customer_workshop_email', 'customers', ['workshop_id', 'email'])
    op.create_unique_constraint('uq_customer_workshop_phone', 'customers', ['workshop_id', 'phone'])
    op.create_foreign_key(None, 'customers', 'workshops', ['workshop_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint('uq_customer_workshop_phone', 'customers', type_='unique')
    op.drop_constraint('uq_customer_workshop_email', 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_workshop_id'), table_name='customers')
    op.drop_index('ix_customer_workshop', table_name='customers')
    op.create_unique_constraint(op.f('customers_email_key'), 'customers', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('customers', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customers', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('customers', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('customers', 'workshop_id')
    op.add_column('cars', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('cars_customer_id_fkey'), 'cars', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_car_regnr', table_name='cars')
    op.drop_index('ix_cc_customer', table_name='customer_cars')
    op.drop_index('ix_cc_car', table_name='customer_cars')
    op.drop_table('customer_cars')
    # ### end Alembic commands ###
