"""fixade plural serviceitemids

Revision ID: a2e3c22491c5
Revises: 7cc1cf810ab3
Create Date: 2025-08-24 15:41:33.030109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e3c22491c5'
down_revision: Union[str, Sequence[str], None] = '7cc1cf810ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_request_service_items',
    sa.Column('booking_request_id', sa.Integer(), nullable=False),
    sa.Column('service_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_item_id'], ['workshop_service_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_request_id', 'service_item_id'),
    sa.UniqueConstraint('booking_request_id', 'service_item_id', name='uq_br_serviceitem')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_request_service_items')
    # ### end Alembic commands ###
