"""Lade till preselect works

Revision ID: ab320e0723e2
Revises: edf3cd0ab26a
Create Date: 2025-08-15 11:10:11.671418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab320e0723e2'
down_revision: Union[str, Sequence[str], None] = 'edf3cd0ab26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop_service_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vehicle_class', sa.Enum('motorcycle', 'small_car', 'sedan', 'suv', 'van', 'pickup', 'light_truck', name='vehicleclass_serviceitem', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('price_type', sa.Enum('hourly', 'fixed', name='servicepricetype', native_enum=False, create_constraint=True), server_default='hourly', nullable=False),
    sa.Column('hourly_rate_ore', sa.Integer(), nullable=True),
    sa.Column('fixed_price_ore', sa.Integer(), nullable=True),
    sa.Column('vat_percent', sa.Integer(), nullable=True),
    sa.Column('default_duration_min', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint("(price_type = 'hourly' AND hourly_rate_ore IS NOT NULL AND fixed_price_ore IS NULL) OR (price_type = 'fixed' AND fixed_price_ore IS NOT NULL AND hourly_rate_ore IS NULL)", name='ck_service_item_price_consistency'),
    sa.CheckConstraint('vat_percent IS NULL OR (vat_percent >= 0 AND vat_percent <= 100)', name='ck_vat_range'),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workshop_id', 'name', name='uq_service_item_workshop_name')
    )
    op.create_index('ix_service_item_workshop', 'workshop_service_items', ['workshop_id'], unique=False)
    op.create_index(op.f('ix_workshop_service_items_id'), 'workshop_service_items', ['id'], unique=False)
    op.create_index(op.f('ix_workshop_service_items_workshop_id'), 'workshop_service_items', ['workshop_id'], unique=False)
    op.add_column('servicetasks', sa.Column('catalog_item_id', sa.Integer(), nullable=True))
    op.add_column('servicetasks', sa.Column('hours', sa.Float(), nullable=True))
    op.add_column('servicetasks', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('servicetasks', sa.Column('unit_price_ore', sa.Integer(), nullable=True))
    op.add_column('servicetasks', sa.Column('line_total_ore', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_servicetasks_catalog_item_id'), 'servicetasks', ['catalog_item_id'], unique=False)
    op.create_index(op.f('ix_servicetasks_service_log_id'), 'servicetasks', ['service_log_id'], unique=False)
    op.create_foreign_key(None, 'servicetasks', 'workshop_service_items', ['catalog_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servicetasks', type_='foreignkey')
    op.drop_index(op.f('ix_servicetasks_service_log_id'), table_name='servicetasks')
    op.drop_index(op.f('ix_servicetasks_catalog_item_id'), table_name='servicetasks')
    op.drop_column('servicetasks', 'line_total_ore')
    op.drop_column('servicetasks', 'unit_price_ore')
    op.drop_column('servicetasks', 'quantity')
    op.drop_column('servicetasks', 'hours')
    op.drop_column('servicetasks', 'catalog_item_id')
    op.drop_index(op.f('ix_workshop_service_items_workshop_id'), table_name='workshop_service_items')
    op.drop_index(op.f('ix_workshop_service_items_id'), table_name='workshop_service_items')
    op.drop_index('ix_service_item_workshop', table_name='workshop_service_items')
    op.drop_table('workshop_service_items')
    # ### end Alembic commands ###
