"""ldladl

Revision ID: f8cf0e7f1ecc
Revises: 4786cb9417cf
Create Date: 2025-08-18 13:13:25.644153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8cf0e7f1ecc'
down_revision: Union[str, Sequence[str], None] = '4786cb9417cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baybookings', sa.Column('price_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baybookings', 'price_type')
    # ### end Alembic commands ###
